### ISSUE TITLE
1.9.1 rc2 broken service on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by seeder** [ansible/ansible-modules-core#1170]
Since ansible was tagged 1.9.1 rc2  "service" module doesn't recognize "upstart" and uses init.d scripts instead

We are running Ubuntu 14.04.2 LTS and it has broken consistently : 

```
  TASK: [app_host/instance | Restart docker service] **************************** 
  failed: [10.1.0.65] => {"failed": true}
  msg:  * Docker is managed via upstart, try using service docker stop
  * Docker is managed via upstart, try using service docker start
```

While it worked without issues  while using rc1 : 

```
 TASK: [app_host/instance | Restart docker service] **************************** 
 changed: [10.1.0.52]
```

Ansible is run with Python 2.7.9 on Alpine Linux. 
If you are familiar with docker , you can pull  environment in which we execute ansible from generik/ansible ( this is not a host with Ubuntu LTS )

**Comment by jswiders** [comment]
I didn't upgrade ansible (1.9.1-1ppa~trusty) but I also have the same problem since yesterday and it's also with docker service.

EDIT - forgot to check my ubuntu software updater - and it did upgrade ansible today from 1.9.0.1-1ppa~trusty to 1.9.1-1ppa~trusty

**Comment by Spunge** [comment]
I just upgraded ansible to version 1.9.1-1ppa~trusty and apparently encountered the same problem with the ssh service.

**Comment by asamasoma** [comment]
We're encountering this issue on the latest ubuntu/trusty64 vagrant box, using ansible-1.9.1-release

**Comment by pmoosh** [comment]
@asamasoma @Spunge Same here - the version I installed was the newest version via pip on a OS X. Reverted back to 1.9.0.1

**Comment by dojric** [comment]
On top of what @Spunge has mentioned, problems are also being encountered with the rsyslog service restarting on a remote Ubuntu machine.

Services unaffected so far I have noticed are: postfix, and auditd. Additionally, it does not seem to affect setting the state as started, only when setting the state as restarted.

**Comment by seeder** [comment]
From what I see, ansible "service" started preferring init.d scripts
init.d is obsolete on every platform - should never be the first pick on any system

to fix the issue with docker , just remove /etc/init.d/docker , not pretty but docker guys should not put it there in the first place when they use upstart

**Comment by errriclee** [comment]
You can trigger this error with 1.9.1 by running:
ansible the_host -m service -a 'name=ssh state=restarted'

Since it seems to be preferring init.d scripts, I looked inside /etc/init.d/ssh on my 14.04.2 instance and see this:

```
  restart)
        check_for_upstart 1
```

and then...

```
check_for_upstart() {
    if init_is_upstart; then
        exit $1
    fi
}
```

So some of Ubuntu's own scripts require upstart (tested by adding an echo to that function).

**Comment by aarnaud** [comment]
same issue with php5-fpm

to force upstart i remove /etc/init.d/php5-fpm, so bad!!

**Comment by jimi-c** [comment]
I believe this patch should correct this (it at least fixes the original reporter's docker issue in my testing):

<pre>
diff --git a/system/service.py b/system/service.py
index db0594f..0a78599 100644
--- a/system/service.py
+++ b/system/service.py
@@ -853,7 +853,7 @@ class LinuxService(Service):
                 # systemd commands take the form <cmd> <action> <name>
                 svc_cmd = self.svc_cmd
                 arguments = "%s %s" % (self.__systemd_unit, arguments)
-        elif self.svc_initscript:
+        elif self.svc_cmd is None and self.svc_initscript:
             # upstart
             svc_cmd = "%s" % self.svc_initscript
 
</pre>

**Comment by RiaanBurger** [comment]
Patch worked for me, thank you (php5-fpm).

**Comment by RiaanBurger** [comment]
And I just went back and it also now works for my rsyslog. Thanks again ;-)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ghost** [comment]
This is not fixed on 1.9.4.

I have  fresh Ubuntu 14.04 LTS; attempting to restart `ssh` service always fails as its referencing sysvinit script when it should be referencing upstart.

If I remove/rename `/etc/init.d/ssh` then it works as expected.

**Comment by abelboldu** [comment]
This is still happening in 2.0 on trusty docker containers
https://travis-ci.org/abelboldu/openstack-glance/jobs/137737287#L1957
