### ISSUE TITLE
Service module fail on systemd host when unit file include \n

### ISSUE THREAD

**Issue by mscherer** [ansible/ansible-modules-core#127]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8 (devel 402d0c37b8) last updated 2014/10/03 12:17:06 (GMT -400)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/03 12:18:36 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/03 12:18:37 (GMT -400)
  configured module search path = /usr/share/ansible
```
##### Environment:

Centos 7 server
##### Summary:

ansible -m service -a "name=mailman state=started enabled=yes" fail on EL7. I spent time to diagnose it, and the cause is the presence of '\n' in the unit file.

```
# grep '\\n' /usr/lib/systemd/system/mailman.service
ExecStop=/bin/sh -c 'echo -e "# DO NOT EDIT THIS FILE!\n#\n# Contents of this file managed by /etc/init.d/mailman\n# Master copy is /usr/lib/mailman/cron/crontab.in" > /etc/cron.d/mailman'
```

 This greatly confuse the module, since  self.execute_command return stdout as 1 single string, whose lines are separated by \n. So if there is already \n in one of the line, this break  on this line ( in get_systemd_status_dict, in system/service.py ):

```
return dict(line.split('=', 1) for line in out.splitlines())
```

Since this return a uneven number of item for dict, a exception is raised. 
##### Steps To Reproduce:

Run the command ansible -m service -a "name=mailman state=started enabled=yes"  on a EL7, with mailman installed.
##### Expected Results:

No failure
##### Actual Results:

```
failed: [mail.example.org] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1412360673.33-152814301059563/service", line 2836, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1412360673.33-152814301059563/service", line 1274, in main
    service.service_enable()
  File "/root/.ansible/tmp/ansible-tmp-1412360673.33-152814301059563/service", line 695, in service_enable
    d = self.get_systemd_status_dict()
  File "/root/.ansible/tmp/ansible-tmp-1412360673.33-152814301059563/service", line 507, in get_systemd_status_dict
    return dict(line.split('=', 1) for line in out.splitlines())
ValueError: dictionary update sequence element #56 has length 1; 2 is required
```

**Comment by Jmainguy** [comment]
I can confirm this is happening, the line that it is failing to parse.

ExecStop={ path=/bin/sh ; argv[]=/bin/sh -c echo -e "# DO NOT EDIT THIS FILE!

**Comment by Jmainguy** [comment]
Created PR https://github.com/ansible/ansible-modules-core/pull/131 which seems to fix this issue.

**Comment by mscherer** [comment]
The PR could indeed fix the issue, but I think it would fail at parsing in others cases. By conflating \n from the file ( ie, written as a escaped new line ) and regular CR, we are losing information. The real fix would be to have out to be a dictionnary, no a string.

**Comment by Jmainguy** [comment]
Well it currently is a dictionary, and the PR continues to use it as a dictionary. The PR throws away any line that does not meet the expected length (2) and at the end returns a dict.

**Comment by abadger** [comment]
@mscherer We seem to be parsing the output of systemctl show $SERVICE here.  It looks like the ExecStop line in systemctl show is formatted like this:

```
ExecStop={ path=/bin/sh ; argv[]=/bin/sh -c echo -e "# DO NOT EDIT THIS FILE!
# 
# Contents of this file managed by /etc/init.d/mailman
# Master copy is /usr/lib/mailman/cron/crontab.in" > /etc/cron.d/mailman ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
```

Putting newlines into a non-script field like Description looks like this:

```
Description=GNU Mailing list manager\nThis is a test\nof badness
```

I think checking whether the = is followed by "{" and if so continuing the line until we encounter a "}\n" would do reasonably well.  We may need to also check for the start of a new property on the next line if we're concerned about false positives.

**Comment by abadger** [comment]
@mscherer, Alright, the commit above implemented the parsing based on {}.  See if it does the trick for you!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by mscherer** [comment]
No, just tested, it still fail ( but maybe if fail for another reason ).

**Comment by Jmainguy** [comment]
@mscherer did you pull in the latest devel code?

**Comment by mscherer** [comment]
I did a git clone on a fresh VM of the main repository. I can try again if your tests didn't failed like mine, i kinda expected the git submodules to be up to date, but as I seldomly use this feature of git and have no idea when and how they are updated, maybe I missed something ( I think I did check with git log, but I am not 100% sure )

**Comment by abadger** [comment]
Trying to start mailman on a fresh VM after this fix did fail but in a different way.  I diagnosed that as mailman not being configured.  I don't recall if that was readily apparent in the output from ansible or if I had to do some digging to find that out.  Since the newline in unit file seemed to be fixed, I didn't go all the way to verify that I could properly configure mailman and then it would start.

If you are getting the same traceback as before, though, then there is something else wrong. If it's something about the repository:

The submodules do have to be checked out explicitly by doing:

```
git clone https://github.com/ansible/ansible.git
cd ansible
git submodule update --init 
source hacking/env-setup
```

(Note -- that will get you the version of the module subdirectories that we've last told git to use with the devel version of ansible.  If you want to follow the HEAD of the modules as well, you need to specify the `--remote` flag to git submodule.  I did make sure that I updated the version of the modules that devel ansible will pull so it shouldn't make a difference in this case.)

If you don't do the explicit checkout I'm not sure whether the devel ansible module loader will fail to find modules or if it will discover modules from any previous versions of ansible you might have installed from system packages.

Also -- I modified the integration tests to check for this case.  If you have run the integration tests before, you can take a look at it to see if there's some other difference between it and the mailman unit file.  That was in this commit: https://github.com/ansible/ansible/commit/56c268ade4013144ae1ee02df2976ad0545a3000  It's part of the "destructive" test set so you would want to run it in its own VM.

**Comment by abadger** [comment]
@mscherer Just let us know if this is resolved, if there's now a different ansible error (and what that might be), or if there's a different way to reproduce this now.

**Comment by Jmainguy** [comment]
@abadger @mscherer I can confirm this fixed it for my testing. 

Centos 7 target

```
---

- name: Install mailman
  yum: name=mailman state=latest

- name: Restart mailman
  service: name=mailman state=restarted enabled=yes
```

```
PLAY [systemd test] *********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [centos7.soh.re]

TASK: [mailman | Install mailman] ********************************************* 
ok: [centos7.soh.re]

TASK: [mailman | Restart mailman] ********************************************* 
changed: [centos7.soh.re]

PLAY RECAP ******************************************************************** 
centos7.soh.re             : ok=3    changed=1    unreachable=0    failed=0   
```

**Comment by mscherer** [comment]
Ok, indeed, it seems fixed. I wonder how I did missed that, sorry for the noise.
