### ISSUE TITLE
service module fails to enable nfs-kernel-server on vivid

### ISSUE THREAD

**Issue by andrewschoen** [ansible/ansible-modules-core#1563]
On a fresh vivid install and using the service module to enable nfs-kernel-server the playbook fails with the following message while trying to enable nfs-kernel-server.

```
msg: Error when trying to enable nfs-kernel-server: rc=1 Synchronizing state for nfs-kernel-server.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nfs-kernel-server defaults
Executing /usr/sbin/update-rc.d nfs-kernel-server enable
Failed to execute operation: No such file or directory
```

Inspecting the node after failure shows that nfs-kernel-server is in fact enabled.

**Comment by bcoca** [comment]
can you check if there is both an init script and an upstart/systemd configuratino?

**Comment by andrewschoen** [comment]
@bcoca Yeah, it looks like there is.  Unless I'm reading this wrong.

```
~$ which systemctl
/bin/systemctl

~$ sudo ls /etc/init.d | grep nfs
mountkernfs.sh
mountnfs-bootclean.sh
mountnfs.sh
nfs-kernel-server
umountnfs.sh

~$ sudo cat /proc/1/comm
systemd

~$ sudo systemctl status nfs-kernel-server
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2015-06-19 16:51:08 EDT; 2 days ago
  Process: 16480 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)
  Process: 16476 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
  Process: 16474 ExecStop=/usr/sbin/rpc.nfsd 0 (code=exited, status=0/SUCCESS)
  Process: 16496 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 16493 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 16496 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Jun 19 16:51:08 XXXX systemd[1]: Starting NFS server and services...
Jun 19 16:51:08 XXXX systemd[1]: Started NFS server and services.


~$ sudo /etc/init.d/nfs-kernel-server status
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2015-06-19 16:51:08 EDT; 2 days ago
  Process: 16480 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)
  Process: 16476 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
  Process: 16474 ExecStop=/usr/sbin/rpc.nfsd 0 (code=exited, status=0/SUCCESS)
  Process: 16496 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 16493 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 16496 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Jun 19 16:51:08 XXXX systemd[1]: Starting NFS server and services...
Jun 19 16:51:08 XXXX systemd[1]: Started NFS server and services.
```

Let me know if you need any other info.

**Comment by andrewschoen** [comment]
Also:

```
$ systemctl list-unit-files | grep kernel-server
nfs-kernel-server.service              enabled

$ systemctl list-unit-files | grep nfs
proc-fs-nfsd.mount                     static
mountkernfs.service                    masked
mountnfs-bootclean.service             masked
mountnfs.service                       masked
nfs-blkmap.service                     static
nfs-config.service                     static
nfs-idmapd.service                     static
nfs-kernel-server.service              enabled
nfs-mountd.service                     static
nfs-server.service                     enabled
nfs-utils.service                      static
umountnfs.service                      masked
nfs-blkmap.target                      disabled
nfs-client.target                      enabled
```

**Comment by bcoca** [comment]
so this is a known bug, which should be fixed in current devel and the upcomming 1.9.2 release, closing this as a duplicate

**Comment by ktdreyer** [comment]
> closing this as a duplicate

as a duplicate of what?

**Comment by bcoca** [comment]
sorry, should have included at least some of the dupes: #915, #1170,#1298, #1533, and some others

fixed by #999

FYI, this should be fixed in 1.9.2 and current devel

**Comment by tomaspinho** [comment]
I'm using ansible 1.9.2 and this just happened on a ubuntu vivid host.
What logs do you need from me?

**Comment by mickengland** [comment]
This is still an issue:
ansible mick$ ansible --version
ansible 1.9.2

TASK: [acceleanu.jenkins | Ensure Jenkins is started and runs on startup.] ***\* 
failed: [10.0.1.15] => {"failed": true}
msg: Error when trying to enable jenkins: rc=1 Synchronizing state for jenkins.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d jenkins defaults
Executing /usr/sbin/update-rc.d jenkins enable
Failed to execute operation: No such file or directory

**Comment by kurtlieber** [comment]
In case someone runs across this bug report, this issue is **not** fixed in 1.9.2, despite what it says here.  See [this bug report](https://github.com/ansible/ansible-modules-core/issues/2846) for more info.  Apparently it's fixed in the (as-yet-unreleased) 2.0 release.
