### ISSUE TITLE
pip module reports changed when installing from github

### ISSUE THREAD

**Issue by michaelrice** [ansible/ansible-modules-core#1645]
In [ansible/1705](https://github.com/ansible/ansible/issues/1705) this issue was reported to be fixed, but I am still having this on 1.9.2

I have the following:

``` yaml
- name: Install pypi-mirror from github
  sudo: yes 
  sudo_user: "{{pypi_user}}"
  pip: virtualenv=/home/{{pypi_user}}/venvs/pypi_server name="git+https://github.com/openstack-infra/pypi-mirror#egg=pypi-mirror-master"
```

No matter how many times I run this it reports "changed"

**Comment by westphahl** [comment]
Same here also with Python 2.7.10 and Ansible 1.9.2

**Comment by dvarrazzo** [comment]
Should be fixed by pull request #1881

**Comment by abadger** [comment]
https://github.com/ansible/ansible-modules-core/pull/2403 has been merged to devel and stable-2.0.  So this should be fixed in 2.0 final.

**Comment by dvarrazzo** [comment]
Thank you @abadger. I guess there is no intention to merge it into ansible 1.9? (that would be pull request #1881). Is there an ETA for ansible 2.0 release?

**Comment by devopsacid** [comment]
I'm running ansible 2.0.1 and I still have issue with pip status changed.
