### ISSUE TITLE
ec2_vpc report a changed on each run 

### ISSUE THREAD

**Issue by mogadanez** [ansible/ansible-modules-core#1717]
sample config

```
 ec2_vpc:
    state: present
    cidr_block: 172.30.0.0/16
    resource_tags: { "Environment":"Development" }
    subnets:
      - cidr: 172.30.1.0/24
        az: c
        resource_tags: { "Environment":"Dev", "Tier" : "Misc" }
      - cidr: 172.30.2.0/24
        az: a
        resource_tags: { "Environment":"Dev", "Tier" : "Main" }
      - cidr: 172.30.3.0/24
        az: b
        resource_tags: { "Environment":"Dev", "Tier" : "Reserve" }
    internet_gateway: True
    route_tables:
        - subnets:
          - 172.30.1.0/24
          - 172.30.2.0/24
          - 172.30.3.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
```

on each run it is report `changed=1`

**Comment by bcoca** [comment]
could this be a dupe of #122 ?

**Comment by mogadanez** [comment]
Looks like, in which version it was fixed?
I'm running 1.9.2

**Comment by ghost** [comment]
Got the same issue with similar configuration on 1.9.2.

**Comment by wyaeld** [comment]
@bcoca I'm still seeing this behaviour on 1.9.4.  Task as follows

``` yaml
- name: Create the VPC
  ec2_vpc:
    state: present
    region: "{{region}}"
    cidr_block: "{{cidr_block}}"
    resource_tags: { Name: "vpc-{{vpc_name}}", Environment: "{{environment}}" }
    subnets:
      - cidr: "{{cidr_subnet_1}}"
        az: "{{zone_1}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-web-2a", Environment: "{{environment}}", Tier: "app" }
      - cidr: "{{cidr_subnet_2}}"
        az: "{{zone_2}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-web-2b", Environment: "{{environment}}", Tier: "app" }
      - cidr: "{{cidr_subnet_3}}"
        az: "{{zone_1}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-db-2a", Environment: "{{environment}}", Tier: "db" }
      - cidr: "{{cidr_subnet_4}}"
        az: "{{zone_2}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-db-2b", Environment: "{{environment}}", Tier: "db" }
    internet_gateway: True
    route_tables:
      - subnets:
          - "{{cidr_subnet_1}}"
          - "{{cidr_subnet_2}}"
          - "{{cidr_subnet_3}}"
          - "{{cidr_subnet_4}}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
  register: vpc
```

resulting in

```
changed: [localhost] => {"changed": true, ....}
```

**Comment by davidstacy** [comment]
same issue here:

boto (2.38.0)
boto3 (1.2.3)
botocore (1.3.15)

ansible --version
ansible 2.0.1.0

playbook:

`````` ---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: vpc
      ec2_vpc:
        state: present
        profile: demo
        cidr_block: 172.22.0.0/16
        resource_tags: { "Environment":"Development" }
        subnets:
          - cidr: 172.22.1.0/24
            az: us-east-1c
            resource_tags: { "Environment":"Dev", "Tier" : "Web" }
          - cidr: 172.22.2.0/24
            az: us-east-1b
            resource_tags: { "Environment":"Dev", "Tier" : "App" }
          - cidr: 172.22.3.0/24
            az: us-east-1a
            resource_tags: { "Environment":"Dev", "Tier" : "DB" }
        internet_gateway: True
        route_tables:
          - subnets:
              - 172.22.2.0/24
              - 172.22.3.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
          - subnets:
              - 172.22.1.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        region: us-east-1
      register: vpc
    - debug: var=vpc```
``````

**Comment by ryansb** [comment]
This bug is fixed on `devel`. The VPC examples above all report `changed=false` on second run. 

```
ansible --version
ansible 2.2.0 (devel 9c505e2fa9) last updated 2016/06/06 07:34:48 (GMT -400)
  lib/ansible/modules/core: (detached HEAD cb1093e085) last updated 2016/06/06 07:34:51 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 66b60ce7cd) last updated 2016/06/06 08:17:03 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```
