### ISSUE TITLE
ec2_elb only looks at first 400 ELBs

### ISSUE THREAD

**Issue by chrisweaver** [ansible/ansible-modules-core#2115]
**Issue Type: Bug Report**

**Ansible Version**: Ansible 1.9.3
**Boto Version**: 2.38.0
**Python Version**: 2.7.5
**Environment**: server OSX Mavericks, destination RHEL 6.6

**Summary**:
The ec2_elb module uses the Boto call "get_all_load_balancers" to dump all ELBs in an account.  However it only looks at the first 400 ELBs.

I verified this by adding debugging to the module to see what it gets back from the Boto call, and it is always exactly 400 ELBs.  However I can see all of our ELBs (currently at 488) when I use the AWS CLI or GUI.

The problem is the ec2_elb module does not make use of the "marker" that the Boto call returns if there are more than 400 ELBs.  The Boto 2.3.8 docs describe the use of an optional "marker" to retrieve the next 400 ELBs:

```
get_all_load_balancers(load_balancer_names=None, marker=None)

marker (string) – Use this only when paginating results and only in follow-up request after you’ve
received a response where the results are truncated. Set this to the value of the Marker element in
the response you just received.
```

**Steps to Reproduce**:
First, you need an account with > 400 ELBs.  Probably rare, but we have one...

Example task:

```
- name: "Register EC2 instance with new ELB"
  local_action:
    module: ec2_elb
    instance_id: my_instance_id
    ec2_elbs: my_test_elb
    state: 'present'
    region: us-east-1
```

Output:

```
TASK: [channel_switch | Register EC2 instance with new ELB] ****************** 
failed: [localhost -> 127.0.0.1] => (item=my_instance_id) => {"failed": true, "item": "my_instance_id"}
msg: ELB my_test_elb does not exist
```

**Comment by bcoca** [comment]
cc @jarv

**Comment by raghu2929** [comment]
Just checking if there is any resolution for this. Or any work around to get the instance added to ELB(using ansible module ec2_elb) when >400 ELB's are present. I am having the same issue, was able to add using AWS CLI.

**Comment by raghu2929** [comment]
For now, i am going with this following work around, executing AWS CLI from my play.
- name: Add EC2 instance to ELB {{ elb_result.elb.name }} using AWS - CLI from within ansible play
  command: "sudo -E aws elb register-instances-with-load-balancer --load-balancer-name {{ elb_result.elb.name }} --instances i-456r3546 --profile <<MyProfileHereIfNeeded>>"
  environment:
    http_proxy: http://{{ proxyUserId }}:{{ proxyPwd }}@proxy.com:port
    https_proxy: http://{{ proxyUserId }}:{{ proxyPwd }}@proxy.com:port

**Comment by bcoca** [comment]
can you test out my patch? I don't have 400+ elbs to look at

**Comment by bcoca** [comment]
@raghu2929 download this file into a 'library' dir adjacent to your play, it will override the built in one.
https://raw.githubusercontent.com/bcoca/ansible-modules-core/85836913e2b34fbffd2479cbe43840528750db85/cloud/amazon/ec2_elb.py

**Comment by raghu2929** [comment]
@bcoca getting this error now. Should it be sys.getsizeof(newelbs) instead of .size?
 File "/Users/.ansible/tmp/ansible-tmp-1446160460.29-67223842836721/ec2_elb", line 269, in _get_instance_lbs
    if newelbs.size == 0:
AttributeError: 'ResultSet' object has no attribute 'size'

**Comment by raghu2929** [comment]
Not sure if sys.getsizeof() is right way of doing but tried with it and now getting different error as mentioned below. "LoadBalancer:test-dev-app-elb" is the LB returned at position 400( tried -vvvv and was able to see all 400 ELB's). Looks like it is failing at the second loop when fetching next set of ELB's with invalid marker being sent? My guess though.

 File "/Users/.ansible/tmp/ansible-tmp-1446161418.31-92108361900344/ec2_elb", line 270, in _get_instance_lbs
    newelbs = elb.get_all_load_balancers(load_balancer_names=None, marker=marker)
  File "/Library/Python/2.7/site-packages/boto-2.38.0-py2.7.egg/boto/ec2/elb/__init__.py", line 135, in get_all_load_balancers
    [('member', LoadBalancer)])
  File "/Library/Python/2.7/site-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>Invalid pagination marker (LoadBalancer:test-dev-app-elb)</Message>
  </Error>
  <RequestId>066865ea-7e95-11e5-b169-c99eb822f01b</RequestId>
</ErrorResponse>

**Comment by bcoca** [comment]
i used a bad example, changed size to len() and pushed update

**Comment by bcoca** [comment]
new url https://raw.githubusercontent.com/bcoca/ansible-modules-core/2db79a2e397f5fd63fc55239a92adebdb9042c6a/cloud/amazon/ec2_elb.py

**Comment by raghu2929** [comment]
Same validation error.. "Invalid pagination marker (LoadBalancer:test-dev-app-elb)".
Why are we sending the marker as last LB retrieved from first loop. Is that how it works with boto? I am referring to code at line 272 which might be causing this.
                marker = newelbs[-1]

**Comment by bcoca** [comment]
that is what i found in the examples online, which I already suspect are wrong since they used .size, reading the boto docs says the marker is returned in the resultset but no mention on how to access.

**Comment by bcoca** [comment]
this time i just read the boto code, this uses properties of resultset object which is what the function returns.
https://raw.githubusercontent.com/bcoca/ansible-modules-core/7f0d86ce56e924f6f02346ec3f0c6aad219fc9de/cloud/amazon/ec2_elb.py

**Comment by raghu2929** [comment]
Yes, i saw that and changed it in my local. Trying to test it now.

**Comment by raghu2929** [comment]
No luck. Back to original error 'msg: ELB MyELB does not exist'. Tried to print the logs but having issues. I can try again tomorrow and see what value is coming for 'newelbs.marker'.

**Comment by raghu2929** [comment]
'newelbs.marker' is printing as None. And i doubt if it is even trying to fetch the next ELB's after first 400. Haven't seen ELB's logged after the first loop.

**Comment by bqbn** [comment]
Have you tried the next_marker property of the ResultSet? It is the marker you can pass to the get_all_load_balancers, and it is set to None if there is no page left. Something like this:

```
elbs = []
marker = None
while True:
    more = elb.get_all_load_balancers(marker=marker)
    marker = more.next_marker
    elbs.extend(more)
    if not marker :
        break
```

**Comment by bcoca** [comment]
yep, seems i misread, updated with next_marker now https://raw.githubusercontent.com/bcoca/ansible-modules-core/8725d0e9283e145139a54954a978e4cfd75bf435/cloud/amazon/ec2_elb.py

**Comment by raghu2929** [comment]
@bcoca I had to move few lines up and down(like below) as mentioned in the snippet by @bqbn to make it work.  Thanks!

 while True:
            try:
                newelbs = elb.get_all_load_balancers(marker=marker)
                marker = newelbs.next_marker
                elbs.extend(newelbs)
                if not marker :
                    break
            except TypeError:
                # Older version of boto do not allow for params
                elbs = elb.get_all_load_balancers()
                break

**Comment by raghu2929** [comment]
@bcoca is this fix merged.

**Comment by ghost** [comment]
I just tried this module but I still get 'msg: ELB MyELB does not exist'.

**Comment by raghu2929** [comment]
@bcoca - can you change the code in ec2_elb.py as I mentioned in my comment above. Looks like merged code is not having this change.

**_Not Working:**_
        while True:
            try:
                newelbs = elb.get_all_load_balancers(marker=marker)
                if not newelbs.is_truncated:
                    break
                elbs.extend(newelbs)
                marker = newelbs.next_marker
            except TypeError:
                # Older version of boto do not allow for params
                elbs = elb.get_all_load_balancers()
                break

**_Working:**_
         while True:
            try:
                newelbs = elb.get_all_load_balancers(marker=marker)
                marker = newelbs.next_marker
                elbs.extend(newelbs)
                if not marker :
                    break
            except TypeError:
                # Older version of boto do not allow for params
                elbs = elb.get_all_load_balancers()
                break

**Comment by ghost** [comment]
@raghu2929 that solved the problem, thank you very much.

**Comment by bcoca** [comment]
fixed via 1d6b31a90f8569029afea5dc8e459529b8c976fb
