### ISSUE TITLE
apt module hangs when aptitude asks for user input

### ISSUE THREAD

**Issue by TamsynUlthara** [ansible/ansible-modules-core#31]
Originally reported by @Debilski as [ansible #7229](https://github.com/ansible/ansible/issues/7229) and closed without resolution:

**Issue Type:**

Bug Report

**Ansible Version:**

ansible 1.6 (devel [`d287179`](https://github.com/ansible/ansible/commit/d287179f7ba3e68fac79b26d08c6995aa3a4ca93)) last updated 2014/04/30 10:47:45 (GMT +200)

**Environment:**

Debian 7

**Summary:**

`aptitude` unfortunately says the following on its man page:

```
-y, --assume-yes
       When a yes/no prompt would be presented, assume that the user entered “yes”. In
       particular, suppresses the prompt that appears when installing, upgrading, or removing
       packages. Prompts for “dangerous” actions, such as removing essential packages, will still
       be displayed. This option overrides -P.
```

This is contrary to `apt-get -y`, which will simply abort after having found a ‘“dangerous” action’.
So, in short using `-y` is not enough to make `aptitude` fully non-interactive and may regularly (e.g. it also chokes on non-authenticated packages) cause ansible to freeze without further notice.

**Steps To Reproduce:**

Example task `apt: upgrade=safe update_cache=yes` to be executed on a machine with e.g. unauthenticated packages.

Real output of `aptitude safe-upgrade -y` on that machine would be:

```
# aptitude safe-upgrade -y
The following packages will be upgraded: 
  iceweasel libmms0 libmozjs24d mcollective-puppet-agent mcollective-puppet-common xulrunner-24.0 
6 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 22.5 MB/22.5 MB of archives. After unpacking 127 kB will be freed.
WARNING: untrusted versions of the following packages will be installed!

Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  xulrunner-24.0 iceweasel libmozjs24d 

Do you want to ignore this warning and proceed anyway?
To continue, enter "Yes"; to abort, enter "No": 
```

… and there it waits for user input.

**Expected Results:**

Ansible should simply fail the apt task.

**Actual Results:**

Ansible hangs and gives no information whatsoever.

**Comment by mpdehaan** [comment]
Perhaps there's another flag to supply answers for this.

**Comment by Jmainguy** [comment]
There is a flag to accept untrusted and not prompt, however I doubt we want to enable that flag by default. @mpdehaan you suggested in https://github.com/ansible/ansible/issues/7229 that if a prompt is generated, ansible should fail and ask the user to try again with force=true if they really want it. I believe this is the best way to do it. I need to look into how to fail on prompts.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Gerst20051** [comment]
i've added the force=true flag but apt module is still hanging!

**Comment by bcoca** [comment]
for some packages that is not enough, you might need to use the debconf module to 'preset' some settings (it happens with the oracle java package for example).

**Comment by Gerst20051** [comment]
I ended up breaking the task into multiple items and that works great. I'm not sure if I wasn't patient enough but it looked like it was hanging for many minutes without any output.

![screen shot 2015-04-09 at 2 59 56 pm](https://cloud.githubusercontent.com/assets/235372/7074579/99fddd42-dec9-11e4-84f7-10999d26fe92.png)
