### ISSUE TITLE
gce_net - creating firewall rule, src_range value seems to get lost or set to empty string

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible-modules-core#330]
I am trying to create firewall rules for internal networks and it seems that the `src_range` value is lost.

Below is information I hope will help reproduce. In the ansible-playbook run output you can see on that `src_range=10.240.0.0/16` is passed to the module but in the error message it claims that the value is `''` 

If any more information is needed please let me know.

System Information:

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.0 (Maipo)

$ rpm -qa | grep libcloud
python-libcloud-0.15.1-1.el7.noarch

$ rpm -qa | grep ansible
ansible-1.7.2-1.el7.noarch
```

vars.yaml

``` yaml
oo_network: "amtestnet"
oo_network_range: "10.240.0.0/16"

```

testing playbook

``` yaml

---
- name: Configure cluster network
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    #oo_network_state: "deleted"
    oo_network_state: "present"

  vars_files:
    - vars.yml

  tasks:
    - name: Create network
      gce_net:
        service_account_email: "{{ gce_service_account_email }}"
        pem_file: "{{ gce_pem_file }}"
        project_id: "{{ gce_project_id }}"
        name: "{{ oo_network }}"
        ipv4_range: "{{ oo_network_range }}"
        state: "{{ oo_network_state }}"
      when: oo_network_state == "present"

    - name: Configure firewall rule - Allow Internal TCP
      gce_net:
        service_account_email: "{{ gce_service_account_email }}"
        pem_file: "{{ gce_pem_file }}"
        project_id: "{{ gce_project_id }}"
        name: "{{ oo_network }}"
        fwname: "{{ oo_network }}-allow-internal"
        src_range: "{{ oo_network_range }}"
        allowed: 'tcp:1-65535'
        state: "{{ oo_network_state }}"
      when: oo_network_state == "present"
```

Verbose ansible-playbook output:

```
PLAY [Configure cluster network] ********************************************** 

TASK: [Create network] ******************************************************** 
<localhost> REMOTE_MODULE gce_net project_id=corded-cable-672 ipv4_range=10.240.0.0/16 state=present pem_file=REDACTED  service_account_email=REDACTED name=amtestnet
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415987867.25-196003741809531 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1415987867.25-196003741809531 && echo $HOME/.ansible/tmp/ansible-tmp-1415987867.25-196003741809531']
<localhost> PUT /tmp/tmpjFyUV4 TO /home/admiller/.ansible/tmp/ansible-tmp-1415987867.25-196003741809531/gce_net
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /home/admiller/.ansible/tmp/ansible-tmp-1415987867.25-196003741809531/gce_net; rm -rf /home/admiller/.ansible/tmp/ansible-tmp-1415987867.25-196003741809531/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "ipv4_range": "10.240.0.0/16", "name": "amtestnet", "state": "present"}

TASK: [Configure firewall rule - Allow Internal TCP] ************************** 
<localhost> REMOTE_MODULE gce_net project_id=corded-cable-672 service_account_email=REDACTED allowed=tcp:1-65535 state=present pem_file=REDACTED src_range=10.240.0.0/16 name=amtestnet fwname=amtestnet-allow-internal
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1415987875.88-78820144516776 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1415987875.88-78820144516776 && echo $HOME/.ansible/tmp/ansible-tmp-1415987875.88-78820144516776']
<localhost> PUT /tmp/tmp2q5HKx TO /home/admiller/.ansible/tmp/ansible-tmp-1415987875.88-78820144516776/gce_net
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /home/admiller/.ansible/tmp/ansible-tmp-1415987875.88-78820144516776/gce_net; rm -rf /home/admiller/.ansible/tmp/ansible-tmp-1415987875.88-78820144516776/ >/dev/null 2>&1']
failed: [localhost] => {"changed": false, "failed": true}
msg: Unexpected response: {'code': None,
 'driver': None,
 'http_code': 400,
 'value': {'domain': 'global',
           'message': "Invalid value for field 'resource.sourceRange': ''.  Must specify either sourceRange or sourceTag.",
           'reason': 'invalid'}}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/admiller/testing.retry

localhost                  : ok=1    changed=1    unreachable=0    failed=1   
```

**Comment by smcavoy-b** [comment]
same story in issue [#252](https://github.com/ansible/ansible-modules-core/issues/252)

**Comment by mpdehaan** [comment]
Any thoughts @ericjohnso  ?

**Comment by mpdehaan** [comment]
err, @erjohnso ^

**Comment by mpdehaan** [comment]
sounds like a dup so going to link these two together and close this one, thanks for report!

**Comment by Erouan50** [comment]
Sorry, it's fixed in which version ?

**Comment by erjohnso** [comment]
@Erouan50 - not fixed yet. The issue is a dup of #252 but still needs love afaik.

**Comment by Erouan50** [comment]
My bad, I didn't see it. Thanks !
