### ISSUE TITLE
ec2_elb_lb throws errors

### ISSUE THREAD

**Issue by wimnat** [ansible/ansible-modules-core#3593]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_elb_lb
##### ANSIBLE VERSION

devel
##### CONFIGURATION

NA
##### OS / ENVIRONMENT

CentOS
##### SUMMARY

It seems that the commit 73586f7ddba7ff33fe25805537af73877ca534b3 has broken the elb_lb module for me.  Mentioning @nbrownus as the author of that commit.

It seems to be because i'm just trying to create an ELB with no instances and the module falls over in multiple places because of NoneType errors.

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 3691, in <module>\r\n    main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 1318, in main\r\n    elb_man.ensure_ok()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 411, in _do_op\r\n    return op(*args, **kwargs)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 499, in ensure_ok\r\n    self._set_instance_ids()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 1150, in _set_instance_ids\r\n    has_instances = [has_instance.id for has_instance in self.elb.instances]\r\nTypeError: 'NoneType' object is not iterable\r\n", "msg": "MODULE FAILURE", "parsed": false}`
##### STEPS TO REPRODUCE

My ELB task looks like this:

```
- name: ELB
  ec2_elb_lb:
    region: "{{ aws_region }}"
    name: myelb
    access_logs:
      s3_location: logs
      s3_prefix: "aws/elb/{{ env }}/{{ type }}"
    health_check:
      ping_protocol: tcp
      ping_port: 80
      response_timeout: 5
      interval: 10
      unhealthy_threshold: 3
      healthy_threshold: 3
    cross_az_load_balancing: yes
    connection_draining_timeout: 60
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
      - protocol: https
        load_balancer_port: 443
        instance_port: 443
        ssl_certificate_id: "arn:aws:iam::{{ aws_account_id }}:server-certificate/{{ env }}.for.com.au"
    security_group_ids: "{{ sec_group.group_id }}"
    subnets: "{{ vpc_subnet_public_fact.subnets|idfromlistofdicts|list }}"
    tags:
      Env: "{{ env }}"
      Type: "{{ type }}"
    state: present

```
##### EXPECTED RESULTS

My ELB to be created
##### ACTUAL RESULTS

I tried various steps to skip the None iteration but it just runs in to another.  

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 3691, in <module>\r\n    main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 1318, in main\r\n    elb_man.ensure_ok()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 411, in _do_op\r\n    return op(_args, *_kwargs)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 499, in ensure_ok\r\n    self._set_instance_ids()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1462349132.85-79515211462816/ec2_elb_lb\", line 1150, in _set_instance_ids\r\n    has_instances = [has_instance.id for has_instance in self.elb.instances]\r\nTypeError: 'NoneType' object is not iterable\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by tyl0r** [comment]
I'm getting the exact same error regardless of specifying instance_ids. Even though I get the TypeError, the LB is still created in AWS but without the instance_ids. What's weird is that, if I run the ec2_elb_lb task again without deleting the LB, it adds the instance_ids and the ELB functions as it should.

**Comment by juliedavila** [comment]
Fixed via https://github.com/ansible/ansible-modules-core/pull/3595

**Comment by einarc** [comment]
Who QA's these things?

**Comment by gmalouf** [comment]
I'm still seeing this issue in ansible 2.1.0.0 - wondering if the backport to 2.0.2.0 didn't get into the 2.1 release.

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ck/f3fq_h2n4ns9c54505d89fz00000gn/T/ansible_m2VhIJ/ansible_module_ec2_elb_lb.py\", line 1328, in <module>\n    main()\n  File \"/var/folders/ck/f3fq_h2n4ns9c54505d89fz00000gn/T/ansible_m2VhIJ/ansible_module_ec2_elb_lb.py\", line 1312, in main\n    elb_man.ensure_ok()\n  File \"/var/folders/ck/f3fq_h2n4ns9c54505d89fz00000gn/T/ansible_m2VhIJ/ansible_module_ec2_elb_lb.py\", line 410, in _do_op\n    return op(*args, **kwargs)\n  File \"/var/folders/ck/f3fq_h2n4ns9c54505d89fz00000gn/T/ansible_m2VhIJ/ansible_module_ec2_elb_lb.py\", line 496, in ensure_ok\n    self._set_backend_policies()\n  File \"/var/folders/ck/f3fq_h2n4ns9c54505d89fz00000gn/T/ansible_m2VhIJ/ansible_module_ec2_elb_lb.py\", line 1090, in _set_backend_policies\n    backend_policies = self._get_backend_policies()\n  File \"/var/folders/ck/f3fq_h2n4ns9c54505d89fz00000gn/T/ansible_m2VhIJ/ansible_module_ec2_elb_lb.py\", line 1082, in _get_backend_policies\n    str(backend.instance_port) + ':' + policy.policy_name for backend in self.elb.backends\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}`
