### ISSUE TITLE
docker_container networks: unable to join containers to a custom network

### ISSUE THREAD

**Issue by genei09** [ansible/ansible-modules-core#3766]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

no configuration change
##### SUMMARY

starting a container with parameter
networks:
  name: custom_net
the new running container is not on the specified network name
docker network ls verifies that the network is present and no error message is observed in ansible
documentation on this feature is minimal and I could not find an example to ensure I am using it appropriately
##### STEPS TO REPRODUCE

simple playbook to startup a container and add it to a specified network

```
- name: Provisioning app container
  docker_container:
    api_version: "{{ docker_api }}"
    name: "{{ container_name }}"
    image: "{{ registry }}/{{ image_name }}:{{ image_tag }}"
    state: "{{ action }}"
    recreate: "{{ app_recreate }}"
    pull: "{{ new_image }}"
    tty: true
    restart_policy: "{{ app_restart_policy }}"
    volumes:
    - "{{ mount_source | default(default_mount) }}"
    networks:
      name: custom_net
```
##### EXPECTED RESULTS

container on the custom_net network
##### ACTUAL RESULTS

container on the default bridge network

**Comment by chouseknecht** [comment]
Fixed with PR #3796

**Comment by HendrikSP** [comment]
~~Please reopen~~

~~This still not fixed correctly: The container will always be connected to the default bridge. `docker run` does behave like this if `--network` is provided at least once~~

Ok, it works, you need to specify `purge_networks: yes`. Sorry :)
