### ISSUE TITLE
Unarchive unable to handle square brackets

### ISSUE THREAD

**Issue by perzizzle** [ansible/ansible-modules-core#4109]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

unarchive.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

RHEL 6.5
##### SUMMARY

unarchive fails to unzip a zip file that contains a file named [Content_Types].xml. This was working in ansible 2.0
##### STEPS TO REPRODUCE

Create a zip file that includes square brackets then run unarchive in a playbook

```
- name: Unzip archive
  unarchive: src=/tmp/test.zip dest=/tmp/  copy=no
```

##### ACTUAL RESULTS

```
fatal: [server-> 127.0.0.1]: FAILED! => {"changed": false, "dest": "/opt/ansible/ansible-test/unarchive/", "extract_results": {"cmd": "/usr/bin/unzip -o \"/tmp/.ansible/ansible-tmp-1467745212.66-101880002030237/source\" \"[Content_Types].xml\" -d \"/opt/ansible/ansible-test/unarchive/\"", "err": "caution: filename not matched:  [Content_Types].xml\n", "out": "Archive:  /tmp/.ansible/ansible-tmp-1467745212.66-101880002030237/source\n", "rc": 11}, "failed": true, "gid": 105, "group": "qa", "handler": "ZipArchive", "mode": "0755", "msg": "failed to unpack /tmp/.ansible/ansible-tmp-1467745212.66-101880002030237/source to /opt/ansible/ansible-test/unarchive/", "owner": "mperzel", "size": 4096, "src": "/tmp/.ansible/ansible-tmp-1467745212.66-101880002030237/source", "state": "directory", "uid": 8164}

```

**Comment by tomaspinho** [comment]
This is related to #3810, ansible expands all included filenames as arguments to unzip and seems not to be escaping them correctly.

**Comment by dagwieers** [comment]
Easy to fix if you know the answer (which you do).
Waiting for the pull request from @tomaspinho ;-)

**Comment by dagwieers** [comment]
Looking at this, the problem seems a bit strange. Simply quoting (what should work and we do) does not work for unzip, you have to quote **and** escape characters.

I modified my code to use `pipes.quote()`, but that fails as well (and is not python3 compatible).

```
[dag@moria ansible.testing]$ /usr/bin/unzip -o 'files/test106.zip' 'test106/some example [Content Types].xml' -d '/tmp'
Archive:  files/test106.zip
caution: filename not matched:  test106/some example [Content Types].xml
[dag@moria ansible.testing]$ /usr/bin/unzip -o 'files/test106.zip' 'test106/some\ example\ \[Content\ Types\].xml' -d '/tmp'
Archive:  files/test106.zip
 extracting: /tmp/test106/some example [Content Types].xml  
```

**Comment by dagwieers** [comment]
Should work now with that new pull-request #4131. Please test !

**Comment by tomaspinho** [comment]
@dagwieers ahah, I'm not really a Python dev, though 😛. Any forseable way to fix #3810? It was closed by the original issuer, but the problem persists. I've had to resort to using unzip as a shell command.
Thanks for this!

**Comment by perzizzle** [comment]
@dagwieers I checked out ansible devel

```
ansible --version
ansible 2.2.0 (devel 95c983438b) last updated 2016/07/18 08:39:40 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/18 08:39:55 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/18 08:39:57 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Then ran my test playbook

```

changed: [mdl-test01 -> 127.0.0.1] => {"changed": true, "check_results": {"unarc                                                                                                                               mp/ansible-tmp-1468849286.97-60346733168622/source\" -d \"/opt/ansible/ansible-t                                                                                                                                /opt/ansible/ansible-test/unarchive/[Content_Types].xml  \n", "rc": 0}, "gid":                                                                                                                                ates": null, "delimiter": null, "dest": "/opt/ansible/ansible-test/unarchive/",                                                                                                                                "test.zip", "owner": null, "regexp": null, "remote_src": null, "selevel": null,                                                                                                                                mode": "0755", "owner": "mperzel", "size": 4096, "src": "/tmp/.ansible/tmp/ansib

PLAY RECAP *********************************************************************
mdl-test01                 : ok=1    changed=1    unreachable=0    failed=0

Traceback (most recent call last):
  File "/home/mperzel/ansible-source/ansible/bin/ansible-playbook", line 129, in
    shutil.rmtree(C.DEFAULT_LOCAL_TMP, True)
AttributeError: 'module' object has no attribute 'DEFAULT_LOCAL_TMP'
```

Not sure what is causing the AttributeError (looking into that might be an issue with my environment). But I can confirm that a zip with square brackets does work with unarchive now.

**Comment by dagwieers** [comment]
It seems as if there is a disconnect between your Ansible version and the modules you are using. Make sure there is no lingering code from an earlier installation.

EDIT: needs_info

**Comment by dagwieers** [comment]
Lacking any feedback, I declare this issue as resolved_by_pr #4131
