### ISSUE TITLE
service 'enabled=yes' parameter is not idempotent

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#875]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel, possibly Ansible 1.8.x
##### Environment:

Ubuntu, Debian Wheezy
##### Summary:

`service: enabled=yes` parameter is not idempotent and always resutls in a changed state. I have bisected the problem to https://github.com/ansible/ansible/commit/dd484e82111e2856af0dbcf6c48f2385743cbd63
##### Steps To Reproduce:

```

---
- hosts: all
  sudo: True
  tasks:

    - name: Start redis and enable
      service: name=redis-server state=started enabled=yes

    - name: Start redis
      service: name=redis-server state=started

    - name: Start redis and enable
      service: name=redis-server state=started enabled=yes

    - name: Start redis
      service: name=redis-server state=started
```
##### Expected Results:

If `redis-server` was previously installed, all tasks should result in "OK" state. If it was installed by the playbook, I expect 1 changed state (first task).
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [coder]

TASK: [Start redis and enable] ************************************************ 
changed: [coder]

TASK: [Start redis] *********************************************************** 
ok: [coder]

TASK: [Start redis and enable] ************************************************ 
changed: [coder]

TASK: [Start redis] *********************************************************** 
ok: [coder]

PLAY RECAP ******************************************************************** 
Start redis and enable -------------------------------------------------- 0.17s
Start redis ------------------------------------------------------------- 0.16s
coder                      : ok=5    changed=2    unreachable=0    failed=0
```

**Comment by abadger** [comment]
ansible/ansible bisection further tracked down to this ansible-modules-core commit: f4a709ad7c122f42b3edd74482dd0d08afc7a95b

**Comment by drybjed** [comment]
@abadger Thank you! :-)

**Comment by abadger** [comment]
Thanks!  I've taken a look and found that the default for changed in that particular function was True.  So we needed to be explicit about setting changed = False when no changes were made.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by drybjed** [comment]
@abadger Unfortunately this bug is still happening on current Ansible devel. :/ Results are the same as before.

**Comment by abadger** [comment]
Diagnosed with @drybjed over IRC... we think the module pointers in the ansible/ansible repo hadn't been updated so it was pulling in pre-fix versions of the modules.  POinters have been updated and things should work now.

**Comment by infernix** [comment]
I just checked out current ansible HEAD with core rev 85c8a892c80b92730831d95fa654ef6d35b0eca0 but this is still happening, despite 939ecd33d4a6706e7ed3d021043143ebff177f8b showing up in the git log.
